also-banip:
  enabled: false

also-ban-all-account:
  enabled: false

ip-alert:
  enabled: false

messages:
  no-permission: "&#FF7171&l⁉ &fУ тебя нет прав на выполнение этой команды."
  console-only: "&#FF7171&l⁉ &fЭту команду нельзя выполнить из консоли."
  flectonepulse-not-ready: "&#FF7171&l⁉ &fFlectonePulse ещё не готов, попробуй позже."

  player-not-found: "&#FF7171&l⁉ &fИгрок &#FFD587%player% &fне найден."

  banip-also-banned: "&#FFDF72⚠ &fДополнительно забанено аккаунтов с этого IP: &#FFD587%count%"
  banip-ip-blocked: "&#FFDF72⚠ &fIP &#FFD587%ip% &fзаблокирован."
  banip-ip-blocked-kick: "&#FF0000Твой IP-адрес заблокирован администрацией сервера."

  unbanip-also-unbanned: "&#FFDF72⚠ &fДополнительно разбанено аккаунтов с этого IP: &#FFD587%count%"
  unbanip-ip-unblocked: "&#FFDF72⚠ &fIP &#FFD587%ip% &fубран из чёрного списка."

  ip-alert-enabled: "&#98fb98&l✔ &fУведомления о заходе с одного IP &#FFD587включены."
  ip-alert-disabled: "&#98fb98&l✔ &fУведомления о заходе с одного IP &#9BCF51выключены."
  ip-alert-notify: "&#FFDF72⚠ &fИгрок &#9BCF51%player% &fзашёл с IP-адреса, который уже использовали другие аккаунты &7(Аккаунтов: %accounts%)"

  reload-success: "&#98fb98&l✔ &fКонфигурация плагина успешно перезагружена!."
